"""De-vig sanity check (Gate 0 B0.1): A/E of de-margined CLOSING probabilities.

A/E = (observed count of outcome) / (sum of de-margined probabilities of that outcome), per
league and method. A clean, calibrated market gives ~1.000. Reference books:
  * Pinnacle close (PS) for seasons <= 2024/25 (non-stale rows only)
  * Betfair Exchange close (BFE) for seasons >= 2024/25
(2024/25 appears under both.) Output: reports/devig_sanity.md
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from fedge.market import METHODS, devig

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    "PS": lambda s: int(s[:4]) <= 2024,
    "BFE": lambda s: int(s[:4]) >= 2024,
}


def _wide(odds: pd.DataFrame, book: str, market: str, sels: list[str]) -> pd.DataFrame:
    o = odds[
        (odds.bookmaker == book)
        & (odds.market == market)
        & (odds.phase == "close")
        & (~odds.stale)
        & (odds.selection.isin(sels))
    ]
    if market == "ou25":
        o = o[o.line.isna() | (o.line == 2.5)]
    w = o.pivot_table(index="match_id", columns="selection", values="price", aggfunc="first")
    return w[sels].dropna()


def ae_rows(matches: pd.DataFrame, odds: pd.DataFrame, market: str) -> pd.DataFrame:
    sels = ["H", "D", "A"] if market == "1x2" else ["over", "under"]
    played = matches[matches.FTHG.notna() & matches.FTAG.notna()].copy()
    if market == "1x2":
        played["y"] = played.FTR
    else:
        played["y"] = np.where(played.FTHG + played.FTAG > 2.5, "over", "under")
    out = []
    for book, season_ok in SOURCES.items():
        w = _wide(odds, book, market, sels)
        m = played[played.match_id.isin(w.index) & played.season.map(season_ok)]
        w = w.loc[m.match_id]
        for method in METHODS:
            p = devig(w.to_numpy(), method).probs
            pdf = pd.DataFrame(p, columns=sels, index=m.index)
            pdf["div"] = m["div"].to_numpy()
            pdf["y"] = m["y"].to_numpy()
            for div, g in [*pdf.groupby("div"), ("ALL", pdf)]:
                row = {"market": market, "book": book, "method": method, "div": div, "n": len(g)}
                for s in sels:
                    row[f"A/E {s}"] = (g.y == s).sum() / g[s].sum()
                out.append(row)
    return pd.DataFrame(out)


def _table(df: pd.DataFrame, sels: list[str]) -> str:
    cols = ["div", "method", "n", *[f"A/E {s}" for s in sels]]
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, r in df.iterrows():
        cells = [str(r["div"]), r["method"], str(int(r["n"]))]
        cells += [f"{r[f'A/E {s}']:.3f}" for s in sels]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def main() -> None:
    interim = ROOT / "data" / "interim"
    matches = pd.read_parquet(interim / "matches.parquet")
    odds = pd.read_parquet(interim / "odds.parquet")
    md = [
        "# De-vig sanity check (Gate 0 B0.1)",
        "",
        "A/E = observed outcome count / sum of de-margined closing probabilities. "
        "A calibrated market gives ~1.000. Non-stale rows only. Pinnacle close is used for "
        "seasons <= 2024/25, Betfair Exchange close for seasons >= 2024/25 (2024/25 is in "
        "both tables). `ALL` pools every league. Generated by `scripts/devig_sanity.py` from "
        "`data/interim/*.parquet`.",
        "",
    ]
    pooled = []
    for market, label, sels in (
        ("1x2", "1X2", ["H", "D", "A"]),
        ("ou25", "Over/Under 2.5", ["over", "under"]),
    ):
        res = ae_rows(matches, odds, market)
        for book in SOURCES:
            sub = res[res.book == book].copy()
            if sub.empty:
                continue
            sub["_all"] = sub["div"] == "ALL"
            sub = sub.sort_values(["_all", "div", "method"], kind="mergesort")
            md += [f"## {label}: {book} close", "", _table(sub, sels), ""]
            for _, r in sub[sub["div"] == "ALL"].iterrows():
                vals = ", ".join(f"{s} {r[f'A/E {s}']:.3f}" for s in sels)
                pooled.append(f"- {label} {book} {r['method']} (n={int(r['n'])}): {vals}")
    md += ["## Summary (pooled over all leagues)", "", *pooled, ""]
    out = ROOT / "reports" / "devig_sanity.md"
    out.write_text("\n".join(md), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
